jobs:
  - job: GenerateReleaseNotes
    displayName: "Generate Release Notes"
    steps:
      - task: XplatGenerateReleaseNotes@4 # version 4 is the latest one
        inputs:
          outputfile: "$(Build.ArtifactStagingDirectory)/releasenotes.md"
          templateLocation: "File" # File means the template is loaded from the path specified under 'templatefile'
          templatefile: "deploy/pipelines/release-notes-template.md"
          checkStage: true # generate release notes since last successful release
          stopOnRedeploy: true
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: True
          getParentsAndChildren: True # get parents and children of linked work items which will be accessible in the template
          getAllParents: true # get all parents of linked work items which will be accessible in the template
          getIndirectPullRequests: False
          stopOnError: False
          emptySetText: "No items found" # text to be returned if no work items found
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/releasenotes.md" # path to publish release notes to
          ArtifactName: "release-notes"
          publishLocation: "Container"
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
        displayName: "Set default Azure DevOps organization and project"
      - bash: az devops wiki page create --path 'Release Notes/$(Build.BuildNumber)' --wiki 'BFU.wiki' --file-path '$(Build.ArtifactStagingDirectory)/releasenotes.md'
        displayName: "Create wiki page for release notes"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
